"""Build the ONSSA knowledge base: scrape -> clean -> chunk -> embed -> FAISS index.

Usage:
    python ingest.py [--refresh] [--limit N] [--dry-run] [--skip-index]

Outputs:
    data/clean/pages.jsonl   cleaned page documents (the reusable knowledge base)
    data/index/              faiss.index, chunks.parquet, sections.parquet, manifest.json
    docs/indexed_pages.md    auto-generated list of indexed pages (deliverable)
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

from onssa_rag import config, vectorstore
from onssa_rag.chunking import split_page
from onssa_rag.cleaning import extract_page
from onssa_rag.scraping import discover_urls, fetch_page, load_pages_config, make_session


def scrape(args) -> tuple[list[dict], list[str], list[str]]:
    session = make_session()
    urls = discover_urls(load_pages_config(), session)
    if args.limit:
        urls = urls[: args.limit]
    print(f"{len(urls)} URLs selected from data/pages.yaml + sitemaps")
    if args.dry_run:
        print("\n".join(urls))
        sys.exit(0)

    docs, skipped, failed = [], [], []
    for i, url in enumerate(urls, 1):
        html = fetch_page(url, session, refresh=args.refresh)
        if html is None:
            failed.append(url)
            print(f"[{i}/{len(urls)}] FAILED   {url}")
            continue
        doc = extract_page(url, html)
        if doc is None:
            skipped.append(url)
            print(f"[{i}/{len(urls)}] skipped  {url} (no substantial content)")
            continue
        doc["fetched_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
        docs.append(doc)
        print(f"[{i}/{len(urls)}] ok       {url} ({len(doc['text'])} chars)")
    return docs, skipped, failed


def write_knowledge_base(docs: list[dict]) -> Path:
    config.CLEAN_DIR.mkdir(parents=True, exist_ok=True)
    out = config.CLEAN_DIR / "pages.jsonl"
    with open(out, "w", encoding="utf-8") as fh:
        for doc in docs:
            fh.write(json.dumps(doc, ensure_ascii=False) + "\n")
    return out


def write_indexed_pages(docs: list[dict]) -> Path:
    """Regenerate docs/indexed_pages.md — the 'list of ONSSA pages indexed' deliverable."""
    lines = [
        "# ONSSA pages indexed",
        "",
        f"{len(docs)} pages — auto-generated by `ingest.py`, do not edit by hand.",
        "",
    ]
    by_section: dict[str, list[dict]] = {}
    for doc in sorted(docs, key=lambda d: d["url"]):
        by_section.setdefault(doc["section"], []).append(doc)
    for section, items in sorted(by_section.items()):
        lines.append(f"## {section} ({len(items)})")
        lines.extend(f"- [{d['title']}]({d['url']})" for d in items)
        lines.append("")
    path = config.PROJECT_ROOT / "docs" / "indexed_pages.md"
    path.parent.mkdir(exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def build_search_index(docs: list[dict]) -> dict:
    all_sections, all_chunks = [], []
    for doc in docs:
        sections, chunks = split_page(doc)
        all_sections.extend(sections)
        all_chunks.extend(chunks)
    print(f"{len(all_sections)} sections, {len(all_chunks)} chunks")

    print(f"embedding with {config.EMBEDDING_MODEL} (first run downloads the model)…")
    from onssa_rag.embeddings import Embedder  # heavy import, only when indexing

    embedder = Embedder()
    vectors = embedder.encode_passages([c["text"] for c in all_chunks], progress=True)

    index = vectorstore.build_index(vectors)
    manifest = {
        "embedding_model": embedder.model_name,
        "dim": embedder.dim,
        "n_pages": len(docs),
        "n_sections": len(all_sections),
        "n_chunks": len(all_chunks),
        "chunk_size": config.CHUNK_SIZE,
        "chunk_overlap": config.CHUNK_OVERLAP,
    }
    vectorstore.save(index, pd.DataFrame(all_chunks), pd.DataFrame(all_sections), manifest)
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the ONSSA knowledge base")
    parser.add_argument("--refresh", action="store_true", help="ignore the local HTML cache")
    parser.add_argument("--limit", type=int, default=None, help="only process the first N URLs")
    parser.add_argument("--dry-run", action="store_true", help="list the selected URLs and exit")
    parser.add_argument("--skip-index", action="store_true", help="stop after cleaning (no embedding)")
    args = parser.parse_args()

    docs, skipped, failed = scrape(args)
    if not docs:
        print("No documents extracted — aborting.")
        return 1

    kb_path = write_knowledge_base(docs)
    pages_md = write_indexed_pages(docs)

    manifest = None
    if not args.skip_index:
        print("\n--- indexing ---")
        manifest = build_search_index(docs)

    print("\n--- ingestion report ---")
    print(f"pages ok:      {len(docs)}")
    print(f"pages skipped: {len(skipped)} (no substantial content)")
    print(f"pages failed:  {len(failed)}")
    for url in failed:
        print(f"  FAILED {url}")
    print(f"knowledge base: {kb_path}")
    print(f"page list:      {pages_md}")
    if manifest:
        print(f"index:          {config.INDEX_DIR} "
              f"({manifest['n_chunks']} vectors, dim {manifest['dim']})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
